### ISSUE TITLE
Package broken on MIController

### ISSUE THREAD

**Issue by ekinney-lang** [kirtonBCIlab/bci-essentials-unity#23]
Restricted permissions from BCIControllerBehaviors has led to MIController.cs being broken on start-up for MIControllerTests.cs 

Also am missing a reference call on the MIControllerTests.CS.

- (using BCIEssentials.Controllers;)

**Comment by mattwehner** [comment]
Fixed in commit [6a648](https://github.com/kirtonBCIlab/bci-essentials-unity/commit/6a6488dd64d8ee8bf31931674c6748aa03fae4c0)
